# Generated by Django 5.2.4 on 2025-07-24 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0002_client_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="client",
            name="team",
        ),
    ]
