# Generated by Django 5.2.4 on 2025-07-24 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0003_remove_client_team"),
        ("team", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="team",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="clients",
                to="team.team",
            ),
            preserve_default=False,
        ),
    ]
