# Generated by Django 5.2.4 on 2025-08-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("client", "0008_client_user"),
        ("userprofile", "0002_userprofile_active_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="client",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                to="client.client",
            ),
            preserve_default=False,
        ),
    ]
