# Generated by Django 5.2.4 on 2025-08-03 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userprofile", "0003_userprofile_client"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="client",
        ),
    ]
