# Generated by Django 5.2.4 on 2025-08-04 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_comment_projectfile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
