# Generated by Django 5.2.4 on 2025-07-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0002_alter_lead_phone"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="prority",
            new_name="priority",
        ),
    ]
