# Generated by Django 5.2.4 on 2025-07-24 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0005_lead_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="team",
        ),
    ]
