# Generated by Django 5.2.4 on 2025-07-24 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lead", "0009_lead_team"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ("name",)},
        ),
    ]
